-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    value DECIMAL(14,2) NOT NULL CHECK (value >= 0),
    image VARCHAR(2083) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    category VARCHAR(255) NOT NULL,
    available BOOLEAN DEFAULT TRUE,
    des VARCHAR(2000) NOT NULL,
    image VARCHAR(2083) NOT NULL
);

CREATE TABLE Sellers (
    id INT NOT NULL PRIMARY KEY GENERATED by DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id)
);

CREATE TABLE Purchases (
    purch_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE PurchasesDetailed (
    purch_id INT NOT NULL REFERENCES Purchases(purch_id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    no_of_items INT NOT NULL,
    fulfilled BOOLEAN NOT NULL
);

CREATE TABLE Inventory (
    sid INT NOT NULL REFERENCES Sellers(id),
    pid INT NOT NULL REFERENCES Products(id),
    invNum INT NOT NULL,
    PRIMARY KEY (sid,pid)
);

CREATE TABLE ProductReviews (
    pid INT NOT NULL REFERENCES Products(id),
    uid INT NOT NULL REFERENCES Users(id),
    text VARCHAR(2000) UNIQUE NOT NULL,
    rating INT NOT NULL,
    numPos INT NOT NULL,
    numNeg INT NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY (pid, uid)
);

CREATE TABLE SellerReviews (
    sid INT NOT NULL REFERENCES Sellers(id),
    uid INT NOT NULL REFERENCES Users(id),
    text VARCHAR(2000) UNIQUE NOT NULL,
    rating INT NOT NULL,
    numPos INT NOT NULL,
    numNeg INT NOT NULL,
    time_written timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY (sid, uid)
);

CREATE TABLE Line_item (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    num_item INT NOT NULL,
    PRIMARY KEY (uid, pid, sid)
);
